export const currencies = [
    { code: 'USD', name: 'Dollar Américain' },
    { code: 'EUR', name: 'Euro' },
    { code: 'JPY', name: 'Yen Japonais' },
    { code: 'GBP', name: 'Livre Sterling' },
    { code: 'AUD', name: 'Dollar Australien' },
    { code: 'CAD', name: 'Dollar Canadien' },
    { code: 'CHF', name: 'Franc Suisse' },
    { code: 'CNY', name: 'Yuan Renminbi Chinois' },
    { code: 'SEK', name: 'Couronne Suédoise' },
    { code: 'NZD', name: 'Dollar Néo-Zélandais' },
    { code: 'MXN', name: 'Peso Mexicain' },
    { code: 'SGD', name: 'Dollar Singapourien' },
    { code: 'HKD', name: 'Dollar de Hong Kong' },
    { code: 'NOK', name: 'Couronne Norvégienne' },
    { code: 'KRW', name: 'Won Sud-Coréen' },
    { code: 'TRY', name: 'Livre Turque' },
    { code: 'RUB', name: 'Rouble Russe' },
    { code: 'INR', name: 'Roupie Indienne' },
    { code: 'BRL', name: 'Real Brésilien' },
    { code: 'ZAR', name: 'Rand Sud-Africain' },
    { code: 'DKK', name: 'Couronne Danoise' },
    { code: 'PLN', name: 'Zloty Polonais' },
    { code: 'TWD', name: 'Nouveau Dollar Taïwanais' },
    { code: 'THB', name: 'Baht Thaïlandais' },
    { code: 'MYR', name: 'Ringgit Malaisien' },
    { code: 'IDR', name: 'Roupie Indonésienne' },
    { code: 'CZK', name: 'Couronne Tchèque' },
    { code: 'HUF', name: 'Forint Hongrois' },
    { code: 'ILS', name: 'Nouveau Shekel Israélien' },
    { code: 'PHP', name: 'Peso Philippin' },
    { code: 'AED', name: 'Dirham des Émirats Arabes Unis' },
    { code: 'SAR', name: 'Riyal Saoudien' },
    { code: 'NGN', name: 'Naira Nigérian' },
    { code: 'ARS', name: 'Peso Argentin' },
    { code: 'CLP', name: 'Peso Chilien' },
    { code: 'PKR', name: 'Roupie Pakistanaise' },
    { code: 'EGP', name: 'Livre Égyptienne' },
    { code: 'BDT', name: 'Taka Bangladais' },
    { code: 'VND', name: 'Dong Vietnamien' },
    { code: 'KWD', name: 'Dinar Koweïtien' },
    { code: 'OMR', name: 'Rial Omanais' },
    { code: 'QAR', name: 'Rial Qatari' },
    { code: 'LKR', name: 'Roupie Sri Lankaise' },
    { code: 'BHD', name: 'Dinar Bahreïni' },
    { code: 'MMK', name: 'Kyat Birman' },
    { code: 'MAD', name: 'Dirham Marocain' },
    { code: 'DZD', name: 'Dinar Algérien' },
    { code: 'TND', name: 'Dinar Tunisien' },
    { code: 'KES', name: 'Shilling Kenyan' },
    { code: 'UGX', name: 'Shilling Ougandais' },
    { code: 'GHS', name: 'Cedi Ghanéen' },
    { code: 'XAF', name: 'Franc CFA BEAC' },
    { code: 'XOF', name: 'Franc CFA BCEAO' },
    { code: 'NAD', name: 'Dollar Namibien' },
    { code: 'MUR', name: 'Roupie Mauricienne' },
    { code: 'SCR', name: 'Roupie Seychelloise' },
    { code: 'BWP', name: 'Pula Botswanais' },
    { code: 'MWK', name: 'Kwacha Malawite' },
    { code: 'ZMW', name: 'Kwacha Zambien' },
    { code: 'MGA', name: 'Ariary Malgache' },
    { code: 'BBD', name: 'Dollar Barbadien' },
    { code: 'JMD', name: 'Dollar Jamaïcain' },
    { code: 'BZD', name: 'Dollar Bélizéen' },
    { code: 'TTD', name: 'Dollar Trinidadien' },
    { code: 'XCD', name: 'Dollar des Caraïbes Orientales' },
    { code: 'HTG', name: 'Gourde Haïtienne' },
    { code: 'PYG', name: 'Guarani Paraguayen' },
    { code: 'UYU', name: 'Peso Uruguayen' },
    { code: 'BOB', name: 'Boliviano' },
    { code: 'VEF', name: 'Bolívar Vénézuélien' },
    { code: 'CRC', name: 'Colón Costaricien' },
    { code: 'NIO', name: 'Córdoba Nicaraguayen' },
    { code: 'HNL', name: 'Lempira Hondurien' },
    { code: 'GTQ', name: 'Quetzal Guatémaltèque' },
    { code: 'PAB', name: 'Balboa Panaméen' },
    { code: 'BND', name: 'Dollar de Brunei' },
    { code: 'PGK', name: 'Kina Papouasienne' },
    { code: 'FJD', name: 'Dollar Fidjien' },
    { code: 'SBD', name: 'Dollar des Îles Salomon' },
    { code: 'TOP', name: 'Paʻanga Tongien' },
    { code: 'WST', name: 'Tala Samoan' },
    { code: 'VUV', name: 'Vatu Vanuatais' },
    { code: 'XPF', name: 'Franc CFP' },
    { code: 'MOP', name: 'Pataca Macanaise' },
    { code: 'PHP', name: 'Peso Philippin' },
    { code: 'LAK', name: 'Kip Laotien' },
    { code: 'KZT', name: 'Tenge Kazakh' },
    { code: 'UZS', name: 'Som Ouzbek' },
    { code: 'KGS', name: 'Som Kirghize' },
    { code: 'MNT', name: 'Tugrik Mongol' },
    { code: 'TJS', name: 'Somoni Tadjik' },
    { code: 'IRR', name: 'Rial Iranien' },
    { code: 'IQD', name: 'Dinar Irakien' },
    { code: 'AFN', name: 'Afghani Afghan' },
    { code: 'AZN', name: 'Manat Azerbaïdjanais' },
    { code: 'AMD', name: 'Dram Arménien' },
    { code: 'GEL', name: 'Lari Géorgien' },
    { code: 'BYN', name: 'Rouble Biélorusse' },
    { code: 'UAH', name: 'Hryvnia Ukrainienne' },
    { code: 'MDL', name: 'Leu Moldave' },
    { code: 'ALL', name: 'Lek Albanais' },
    { code: 'BAM', name: 'Mark Convertible' },
    { code: 'MKD', name: 'Denar Macédonien' },
    { code: 'RSD', name: 'Dinar Serbe' },
    { code: 'MVR', name: 'Rufiyaa Maldivienne' },
    { code: 'LKR', name: 'Roupie Sri Lankaise' },
    { code: 'NPR', name: 'Roupie Népalais' },
    { code: 'BTN', name: 'Ngultrum Bhoutanais' },
    { code: 'BIF', name: 'Franc Burundais' },
    { code: 'CDF', name: 'Franc Congolais' },
    { code: 'GNF', name: 'Franc Guinéen' },
    { code: 'KMF', name: 'Franc Comorien' },
    { code: 'RWF', name: 'Franc Rwandais' },
    { code: 'DJF', name: 'Franc Djiboutien' },
    { code: 'MGA', name: 'Ariary Malgache' },
    { code: 'SCR', name: 'Roupie Seychelloise' },
    { code: 'ZMW', name: 'Kwacha Zambien' },
    { code: 'MWK', name: 'Kwacha Malawite' },
    { code: 'TZS', name: 'Shilling Tanzanien' },
    { code: 'UGX', name: 'Shilling Ougandais' },
    { code: 'SOS', name: 'Shilling Somalien' },
    { code: 'KES', name: 'Shilling Kenyan' },
    { code: 'ZAR', name: 'Rand Sud-Africain' },
    { code: 'GHS', name: 'Cedi Ghanéen' },
    { code: 'XAF', name: 'Franc CFA BEAC' },
    { code: 'XOF', name: 'Franc CFA BCEAO' },
    { code: 'MZN', name: 'Metical Mozambicain' },
    { code: 'AOA', name: 'Kwanza Angolais' },
    { code: 'ZWL', name: 'Dollar Zimbabwéen' },
    { code: 'SZL', name: 'Lilangeni Swazi' },
    { code: 'LSL', name: 'Loti Lesothan' },
    { code: 'MAD', name: 'Dirham Marocain' },
    { code: 'DZD', name: 'Dinar Algérien' },
    { code: 'TND', name: 'Dinar Tunisien' },
    { code: 'LYD', name: 'Dinar Libyen' },
    { code: 'SDG', name: 'Livre Soudanaise' },
    { code: 'MRU', name: 'Ouguiya Mauritanien' },
    { code: 'MRO', name: 'Ouguiya Mauritanien (ancien)' },
    { code: 'GMD', name: 'Dalasi Gambien' },
    { code: 'SLL', name: 'Leone Sierra-Léonais' },
    { code: 'NAD', name: 'Dollar Namibien' },
    { code: 'BWP', name: 'Pula Botswanais' },
    { code: 'ETB', name: 'Birr Éthiopien' },
    { code: 'SOS', name: 'Shilling Somalien' },
    { code: 'ERN', name: 'Nakfa Érythréen' },
    { code: 'SSP', name: 'Livre Sud-Soudanaise' },
];
